[[target]]
name = 'windcore'
type = 'static_library'
dependencies = [
    '@plugin:llvm-config',
]
include_dirs = [
    '.',
]
sources = [
    'core/*.c',
    'token/*.c',
]


[[target]]
name = 'windc'
type = 'executable'
dependencies = [
    'windcore',
]
include_dirs = [
    '.',
    'windc/',
]
sources = [
    'windc/*.c',
]